### ISSUE TITLE
Cultivate ideas for new projects

### ISSUE THREAD

**Issue by wdoug** [codefordenver/org#103]
Let's research possible projects. Things to look into include investigating other projects from the Code for America network.

**Comment by dfackler** [comment]
We could possibly create a 'pitch' to introduce ourselves to other local nonprofits in CNA to get the word out. That way we can get some asks from other organizations around how they could benefit from our services. We would need to make sure to give guidelines on what valid projects are and filter projects before bringing them to the group. 

We could also try to get CNA to send out an email blast to members advertising our services and start filling up our project pipeline. Alternatively we could try to at least get the member emails from them or using Willy's Node app.

**Comment by dfackler** [comment]
Mira also mentioned that the Denver Public Library would be a good resource to use.

**Comment by dfackler** [comment]
Willy mentioned finding an "area of interest" and reaching out to organizations to understand their workflow and try to come up with a project to help them. 

He also mentioned deploying other brigades' code locally.

**Comment by wdoug** [comment]
I'm going to say we finished the initial stage of this we had planned.
