### ISSUE TITLE
Look into Restaurant Donations for meals

### ISSUE THREAD

**Issue by Mira321** [codefordenver/org#108]

**Comment by jhernandez2017** [comment]
Hey Team, 

Please follow this link for potential food donors Excel file where we can organize our food donations projects. 

It is structured like the donor list Excel file, so we will be able to assign the restaurants to certain volunteers. 

https://docs.google.com/spreadsheets/d/17NBvjOGdPqF7eZgF7fy0xR5SyCV-Nwj89iEyIuPoqoI/edit?usp=sharing
