### ISSUE TITLE
Free Tech Tools Talk--10/30/17; 3pm - 4:30pm

### ISSUE THREAD

**Issue by dfackler** [codefordenver/org#109]

**Comment by dfackler** [comment]
Good Afternoon David Fackler,
 
Thank you for submitting a session proposal. We are delighted to include your “Free Tech Tools for Nonprofits:  What's Out There and What You Need to Know” presentation in this year’s conference lineup for the Fall Conference and Exhibition: Nonprofit of Influence on October 30 & 31, 2017!
 
SESSION DETAILS
Session Title: Free Tech Tools for Nonprofits:  What's Out There and What You Need to Know
Session Track:  IT
Training Level: Beginner
Start Date/Time:  Monday, 3:00pm
End Date/Time:  Monday, 4:30pm
Location: Sheraton Denver Downtown Hotel
 
2017 FALL CONFERENCE THEME
Influence is the power to make change and shape the future. In 2017, nonprofits across the country are taking a stand for their mission and engaging those they serve making their voices heard.    
The Nonprofit of Influence: 2017 Fall Conference is the time for nonprofit and business professionals to join together and discuss vital questions ensuring Colorado has the nation’s most effective, vibrant and innovative nonprofit community that is essential to the high quality of life in our state. Join more than 950 nonprofit, business, and community leaders for two full days of learning, idea-sharing, skill-building and networking all in support of Colorado’s nonprofit community! The Fall Conference is Colorado Nonprofit Association’s premier, annual event open to all professionals serving Colorado’s nonprofit community.
Please consider integrating this year’s theme when you are preparing your presentation.
NEXT STEPS
1.                   Please reply to this email by COB Wednesday, May 31st to let us know you received it AND to confirm your availability for the day & time listed above. The time shown above is your session time; please plan to arrive early to check in, set up, etc.

2.                   When you submitted your proposal online you agreed to the Speaking Agreement. Please review and let us know if you believe you can no longer agree to the terms.
·         Presenting is a voluntary act: Speaker understands presenters are asked to facilitate their discussion pro bono, and no honorarium, stipend, or compensation will be paid. The Association is not responsible for, nor will it pay for any travel.
·         Selling or Promoting Products and Services: Speaker agrees to provide educational information only and not promote or sell products or services. Speakers who violate this policy will not be invited to speak at future workshops or other Association events.
·         Change of Plans: Speaker agrees to notify the Association immediately if plans change and speaker is unable to present.
·         Session Rooms and Equipment: Session rooms and available equipment will be determined and assigned at the sole discretion of the Colorado Nonprofit Association.
·         Indemnification and Hold Harmless: Speaker agrees to indemnify, hold harmless, and defend the Colorado Nonprofit Association and its respective employees, officers, and agents for any and all alleged liability, loss, damage, claim, cause of action or expense resulting from speaker's misstatement of fact. In addition, Speaker shall not use copyrighted material in a presentation without obtaining a prior written permission from author.

3.                   You are receiving this message because you are listed as the main presenter for your conference session, Free Tech Tools for Nonprofits:  What's Out There and What You Need to Know. If your session includes co-presenters, please pass this information along to them. 

4.                   As soon as I hear confirmation from you about your availability, we will be in touch to confirm your session details and coordinate logistics later this Summer.
 
Each year, we’re honored and grateful to receive over 200 fantastic session proposals from prospective presenters. Thank you again for the time you put into your proposal and of course thank you for your interest in partnering with the Colorado Nonprofit Association. We look forward to working with you!
 
Thank you,
BillieAnne

**Comment by karenderrickdavis** [comment]
Awesome!

**Comment by karenderrickdavis** [comment]
David, this is you and Willy presenting, right?
