### ISSUE TITLE
Write Email to Ask for Projects

### ISSUE THREAD

**Issue by dfackler** [codefordenver/org#110]
We want an email to have external organizations come to us with a project ideas. Write up a template.

**Comment by jhernandez2017** [comment]
Hello @dfackler is this the current version of this project. https://docs.google.com/document/u/4/d/1g49ygKr_BWV_4incl5ENB1vH83QEPyd4ISVypaMBlXM/edit?usp=drive_web

**Comment by jhernandez2017** [comment]
This is the PDF that can answer what we do https://drive.google.com/drive/u/4/folders/0B521r37N9p-OMnh1dW92aFFiMUE.

**Comment by jhernandez2017** [comment]
I will be looking to work with a new member called Chris on this task for the 2 weeks.

**Comment by maverickg59** [comment]
We shall collaborate on this and make it awesome!

**Comment by Mira321** [comment]
See this doc which is the original doc David Frackler did with added comments and is now a "working doc" - to be copied and put into final version in other docs:  
https://docs.google.com/document/d/1ox4kD5turZOKkQpscGiGHtXpGjP6bQYAhE2Y_zTzf-Q/edit

**Comment by jhernandez2017** [comment]
Hello Team, 

I have added my template to the working doc below. Let me know what you think. 

https://docs.google.com/document/d/1ox4kD5turZOKkQpscGiGHtXpGjP6bQYAhE2Y_zTzf-Q/edit

**Comment by dfackler** [comment]
I like it! We may want to be careful about the specific types of projects we suggest because I think Willy has mentioned steering clear of website upkeep/design? I could be wrong though
