### ISSUE TITLE
Mile High Data Day 2017--9/14/2017

### ISSUE THREAD

**Issue by karenderrickdavis** [codefordenver/org#111]
Code for Denver has a session in the afternoon.

**Comment by karenderrickdavis** [comment]
Potential topics:
* Kobotools (what it is and what you might use it for)
* Effective Altruism
* review of CfD past and current projects (any project ideas?)

**Comment by karenderrickdavis** [comment]
Meeting set with Matt Berry (Piton) on 8/23 to discuss session content.

**Comment by jhernandez2017** [comment]
Hey @karenderrickdavis I would love to help out with either the mini-pitches or effective altruism. How long would it have to be and can I make it out of Prezi?

**Comment by karenderrickdavis** [comment]
@jhernandez2017 Great to know!  We will be finalizing the session tomorrow morning.  I'll post an update after the meeting.
