### ISSUE TITLE
Denver Startup Week Session--9/26/17; 4p-6pm

### ISSUE THREAD

**Issue by karenderrickdavis** [codefordenver/org#113]
"Applying Your Skills for Good with Code for Denver"--Showcasing projects and recruiting more volunteers.

**Comment by jhernandez2017** [comment]
Hey @karenderrickdavis I would LOVE to help out with the Trello presentation. Can you let me know what you need for this presentation...Also, can I make it out of Prezi or does Powerpoint have to be the main presentational tool :)

**Comment by karenderrickdavis** [comment]
@jhernandez2017 this is not the Trello presentation. This is just a "recruitment" presentation to get more vols for Code for Denver.

**Comment by karenderrickdavis** [comment]
Ideas for presentation:
[] intro to code for america and our local brigade (video, 2016 report)
[] demo of a couple of our best projects (FFC, Ecocycle project)
[] explanation of current projects (what they are, what tech is being used)
[] brief explanation of how we vet projects
[] an exercise of some sort to learn the interests (community challenges) of the participants

**Comment by jhernandez2017** [comment]
Hello team, 

Please follow this link for the presentation talking points. 

https://docs.google.com/document/d/1rX-a_A7f3TSIxo3iL-_4lBBZHw5U3tyjm_pzL0XUenQ/edit

Feel free to edit as you see fit.
