### ISSUE TITLE
CFD Site Content Migration

### ISSUE THREAD

**Issue by dviramontes** [codefordenver/org#116]
In order to launch our new [beta.codefordenver.org](beta.codefordenver.org) from [codefordenver.org](http://codefordenver.org) version of the site we need to be able to move the following content over to the WP install:

- [ ]  links to 2015 & 2016 EOY reports
- [ ]  video(s)
- [ ]  twitter feed
- [ ] what am i missing ?

**Comment by eemshi** [comment]
re: link to EOY reports,
the permalinks are:
http://codefordenver.github.io/code-for-denver-site/2015
http://codefordenver.github.io/code-for-denver-site/2016

after we switch the dns over, we could set up redirects in namecheap to mask those urls

**Comment by wdoug** [comment]
I have moved this to the specific board for the new site: https://github.com/codefordenver/codefordenver.org/issues/6
