### ISSUE TITLE
Investigate adding a bot to flowdock

### ISSUE THREAD

**Issue by wdoug** [codefordenver/org#13]
As a member of Code for Denver, I want to be able to interact with a bot for tedious tasks, and humorous interactions.

**Comment by wdoug** [comment]
Rally uses a clone of [Hubot](https://hubot.github.com/), and it is great

**Comment by dviramontes** [comment]
looking into [this clojure lib](https://github.com/RallySoftware/jarvis) too

**Comment by dviramontes** [comment]
started https://github.com/codefordenver/flowdock-bot
