### ISSUE TITLE
Transition out of flowdock

### ISSUE THREAD

**Issue by dviramontes** [codefordenver/org#139]
- not slack because of pricing
- [x] how long does history stick around ?
- [x] investigate mattermost
- [x] investigate discord

**Comment by anotherpatrickcollins** [comment]
Seems like we've landed on Discord. 

There's an export function for Flowdock if we need any of the past chats. I peeked and it doesn't seem there's any import function for Discord to keep that data in the chats through the migration so it'll likely be for archive purposes only.
https://www.flowdock.com/organizations/42064/flows

Let's make sure we have Discord set up with the permissions and default channels so we can let the general public join as they're interested (@jberns can you take this?)

And can we install a bot for simple commands like !agenda or !resources for channels so when someone new joins they can just populate the links they need that way? Maybe https://dyno.gg/

**Comment by anotherpatrickcollins** [comment]
Need to update references to Flowdock in:
- Agenda
- Onboarding
- Codefordenver.org
- Meetup
- Members Site

**Comment by jberns** [comment]
Yea, I can work on this tonight!

**Comment by anotherpatrickcollins** [comment]
Flowdock final steps to force migration:

- Lock channels to read only.
- Add channel discord invites for folks who still log into Flowdock.

**Comment by anotherpatrickcollins** [comment]
Can't lock flows, and can't give channel invites because of our membership roles in discord (someone would have to already be on discord in the right role to join the specific channel).

So I think this is done! 

A+ team.
