### ISSUE TITLE
Reinvestigate member skills/interests form

### ISSUE THREAD

**Issue by wdoug** [codefordenver/org#15]
This form was a great idea: https://docs.google.com/forms/d/1PZTUcrPInQclU-7riH9xthcXxHGzv0EKeKVCqaXAHKw

It would be great to reinvestigate this. Ultimately, I think it would be best as an actual app that we make (although the amount of effort could quickly explode).

**Comment by jenshurley** [comment]
Here's a first pass at process definition for gathering information about skills and interests as a process based on what I've heard at meetings. 

#Initial skills info
When: Signup for CfD on Meetup - gather initial information - 
example -- CfA's Brigade form (name, email, checkboxes for 'work in government', 'technologist', 'attend local brigade') 

#Invite to give more detailed skills information
When: First CfD Event or Meeting attended
.capture skills as part of attendance/sign in (SF brigade has flask app for this?)  https://github.com/codeforamerica/brigade/issues/344
.fill out skills form as part of onboarding process (at the same time as getting invited to flowdock, waffle) 

#Reminder to update skills and interests

#Targeted invites to participate in project - skills needed 
This functionality was built at NDoCH - now need wording for email templates

**Comment by wdoug** [comment]
Found on codefordenver.org/members
Direct link: https://docs.google.com/forms/d/e/1FAIpQLSc92b32sfo011b8I-QiP7GtWSA2prQ0UPSmn6LxXb6wdpjtQg/viewform
