### ISSUE TITLE
National Day of Civic Hacking - September 21, 2019

### ISSUE THREAD

**Issue by anotherpatrickcollins** [codefordenver/org#155]

**Comment by amaliebarras** [comment]
Hey guys! Curious if Code for Denver will be hosting a NDoCH event this year and if so, where I can find more info.

**Comment by anotherpatrickcollins** [comment]
> Hey guys! Curious if Code for Denver will be hosting a NDoCH event this year and if so, where I can find more info.

Hey! We are. Still gathering some info but you can see date, theme, and activities at http://build.codefordenver.org
