### ISSUE TITLE
Consolidate and Update CfD information

### ISSUE THREAD

**Issue by wdoug** [codefordenver/org#17]
As a member of CfD, I want updated information centralized in an easy to find location, so I can know what I'm doing and how to contribute.
- [x] Update new meetup member email
- [x] Add CfD website url to meetup page
- [ ] Make website more centralized source of info and means of contact (probably redirect through meetup)

**Comment by wdoug** [comment]
Related to https://github.com/codefordenver/code-for-denver-site/issues/3

**Comment by wdoug** [comment]
@dviramontes at one point worked on pulling in documents through the Drive API

**Comment by dviramontes** [comment]
look at : https://github.com/codefordenver/org/blob/builder/src/app.jsx

**Comment by wdoug** [comment]
@switzersc, what is the status of this?

**Comment by wdoug** [comment]
I'm going to close this, as it is super old. If there is anything remaining that we want to do,  we can have a separate card.
