### ISSUE TITLE
Figure out what we want to do to improve the onboarding process

### ISSUE THREAD

**Issue by wdoug** [codefordenver/org#18]
As a new member or CfD, onboarding can be complicated and overwhelming, especially if the brigade is in the middle of a project.

**Comment by jenshurley** [comment]
Working on a diagram here: 
https://docs.google.com/drawings/d/1-Ogb3GAxAwkRguXoVXMntdmgw7Kz0qgGGBTgIq_SCvQ/edit

**Comment by jenshurley** [comment]
#Onboarding in context
How does onboarding process fit into larger CfD membership journey?  
https://www.lucidchart.com/invitations/accept/fab7a10c-d846-406f-a716-b4edea1fece6

**Comment by jenshurley** [comment]
Some other ideas I've heard at meetings: 
 - instructions on setting up your machine on Meetup (i.e., install git, etc. -- Girl Develop It does this.)
- part of onboarding process could be having people make a pull request to add their name to the website.

**Comment by jenshurley** [comment]
move to Done? Reassign? -- now this investigation is part of Meetup Mashup project

**Comment by jenshurley** [comment]
@biodavis started onboarding Pomodoro.  :awesome:
