### ISSUE TITLE
Gain feedback from partners

### ISSUE THREAD

**Issue by karenderrickdavis** [codefordenver/org#24]
As the CfD organization, we want to constantly improve our process and learn, therefore we will get feedback from past partners
- [x] create survey
- [x] send survey
- [ ] face-to-face interviews with past partners

**Comment by karenderrickdavis** [comment]
11/30 messaged Brendan (RMMFI) via Flowdock

**Comment by karenderrickdavis** [comment]
have responses from 3/4 of partner organizations.

**Comment by wdoug** [comment]
@karenderrickdavis did we ever hear anything from SOL?
