### ISSUE TITLE
gain feedback from brigade members

### ISSUE THREAD

**Issue by karenderrickdavis** [codefordenver/org#32]

**Comment by jenshurley** [comment]
I was going to put Year-in-Review images together, but then I thought, hey, I'll add them to the survey to encourage responses.  [Here's the survey with pictures](https://c4d.typeform.com/to/ZOxyAo).  Then I'll post a photo (for visibility) and @-mention everyone I can think of from this year on flowdock.   
It didn't come out quite how I'd imagined, and  if it's even something that would help.  But I got more practice with Typeform templates.
