### ISSUE TITLE
Fill out Code for America 2016 strategic planning doc

### ISSUE THREAD

**Issue by wdoug** [codefordenver/org#34]
This is a requirement for being an 'official brigade', and is also a good framework for defining our plans.  This is current document https://docs.google.com/document/d/11Gd2QseyBdgsUhmqSqTXXnqQmR7zrQYQKbeE6tqi2jA/edit 

[**CfA Template document to fork**](https://docs.google.com/document/d/1z-WhbzjXVHLlBB-JDmx6MaGNfY-AudTgE7xd-qsaU-k/edit#)

**Comment by biodavis** [comment]
Brian create draft and provide to willy, greg, rae and karen for fill in feedback

**Comment by biodavis** [comment]
Derek, Evan and Brian working on it Dec 21, 2105
