### ISSUE TITLE
explore ways for introducing potential projects

### ISSUE THREAD

**Issue by karenderrickdavis** [codefordenver/org#41]
with our new "rolling" schedule, how will potential projects be introduced and vetted in an organized way?

**Comment by karenderrickdavis** [comment]
one idea is to have a standing time, like 1st mondays, where we will open the floor for lightning talks

**Comment by jenshurley** [comment]
process ideas from [Jan 11 meeting](https://docs.google.com/document/d/1kIhdl1ONPqndOuk2MfAgn4QmH_NxpY8zo5v9dfHdXFs/edit#)

**Comment by jenshurley** [comment]
"Evaluating Your Best Ideas" from  +Acumen course on Human-Centered Design course: 

One possibility is to use the lean coffee app to vote on next projects using [some quick guiding questions](https://goo.gl/photos/qQfiV5Ya7qsb49gJA)

**Comment by wdoug** [comment]
@jenshurley is it cool if we close this now? Perhaps we could add the idea about the lean coffee app to the project bootstrapper waffle?

**Comment by jenshurley** [comment]
Absolutely
