### ISSUE TITLE
Write up project guidelines

### ISSUE THREAD

**Issue by wdoug** [codefordenver/org#44]
Summarize what we discussed as a group Jan. 4, 2015

**Comment by Mira321** [comment]
Darren did this.  See the Org flow.  Here is the link to the doc he created that is being discussed for use:    https://docs.google.com/document/d/1gNo1ZgfMN-3Qz_xUcROvuyF67yBn9ZdlkRaotPLYUJk/edit#heading=h.cj9lh2y6ma9h
