### ISSUE TITLE
compile info for 2016 report

### ISSUE THREAD

**Issue by karenderrickdavis** [codefordenver/org#66]

**Comment by karenderrickdavis** [comment]
report is primarily for fundraising

**Comment by karenderrickdavis** [comment]
- [ ] volunteer stats (number, hours, demographics)
- [ ] brief summary of each 2016 project
- [ ] update of Fresh Food Connect (leveraging and continuation of our work)
- [ ] budget
- [ ] check in with 2015 projects
- [ ] activity (lines of code)
- [ ] number of google drive docs
- [ ] number of events

**Comment by Mira321** [comment]
I started a slide show in Google Docs - https://docs.google.com/presentation/d/1YhN6korABoUOjphJvIjOjGKm8f7FaS-PRj4HJzPOPu0/edit#slide=id.p
