### ISSUE TITLE
Upload EOY report to Website

### ISSUE THREAD

**Issue by Mira321** [codefordenver/org#88]

**Comment by Mira321** [comment]
Trinh is resizing the PDF to send to Willy to upload to the website

**Comment by wdoug** [comment]
As an image, is the resolution high enough?

**Comment by wdoug** [comment]
I wonder if leaving it as a pdf is better.

**Comment by wdoug** [comment]
This is visible on http://www.codefordenver.org/2016report
Still need to link to it from somewhere on the website.

**Comment by wdoug** [comment]
Let's limit the max width

**Comment by dfackler** [comment]
Michelle uploaded this to website and demo'd today (4/17/17). Closing ticket.
