### ISSUE TITLE
Clean up Google Drive folders

### ISSUE THREAD

**Issue by genelle** [codefordenver/org#89]
Refer to David's document for cleaning up the folders:
https://docs.google.com/document/d/1qNMiOaFh0AC0D0YvEt4vPbS-Px48tjGyM5cTf1U3kLY/edit?usp=sharing

1) Mock up how we want to organize the drive folders (link above)
2) reorganize the ORG folder only
3) Come back and finalize how we want it organized
4) Disseminate information to the project teams

**Comment by genelle** [comment]
Do I need to identify a time to update this to make sure no one is in the folders?

**Comment by Mira321** [comment]
I added most of the new folders  per the reorganization doc David F created.  Did not move any files - just created folders.

**Comment by genelle** [comment]
Mira - You should be able to move the files as well. Google Drive is specifically set up to not break links when you move a file to a different folder, nor interrupt anyone editing a document if it is moved while open.
