### ISSUE TITLE
Submit Proposal by 4/30 to Co NonProf Assoc Presentation of Session(s) for Oct 30-31

### ISSUE THREAD

**Issue by Mira321** [codefordenver/org#96]

**Comment by karenderrickdavis** [comment]
Ideas:
workshop on free tech tools available to nonprofits: what they are, what they can do, pros and cons

**Comment by karenderrickdavis** [comment]
Last years' list of workshops (for inspiration): https://www.coloradononprofits.org/sites/default/files/attachments/Final%20Preview.pdf

**Comment by dfackler** [comment]
Ideas:
Effectively partnering with existing organizations to benefit the community
Applying Agile processes to non-profits
Handling onboarding and project management for volunteer based non-profits
Running local branches of nationwide organizations

**Comment by dfackler** [comment]
![screen shot 2017-04-10 at 8 56 17 pm](https://cloud.githubusercontent.com/assets/1988180/24891036/95fe753c-1e30-11e7-91af-9be0fefe88f7.png)
![screen shot 2017-04-10 at 8 56 10 pm](https://cloud.githubusercontent.com/assets/1988180/24891035/95fe3e3c-1e30-11e7-839d-945c28f3ecf9.png)

**Comment by dfackler** [comment]
Added Free Tech Tools for Nonprofits:  What's Out There and What You Need to Know.

**Comment by karenderrickdavis** [comment]
Submitted proposal about Agile.
