### ISSUE TITLE
Create Fundraising Strategy

### ISSUE THREAD

**Issue by wdoug** [codefordenver/org#99]

**Comment by Mira321** [comment]
Create and/or use Prospect excel doc for potential people/companies/orgs to approach

**Comment by Mira321** [comment]
Assign names of people to groups/entities who will make the contact

**Comment by Mira321** [comment]
Finalize the literature/emails/docs used to send out - docs with logo, EOY etc and specifics re: what contributions will go toward.

**Comment by Mira321** [comment]
Plan the agreed upon way of presenting CFD.
